<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Skill;
use Illuminate\Support\Facades\DB;

class SkillSeeder extends Seeder
{
    public function run()
    {
        DB::beginTransaction();

        try {
            $skills = [
                // Programming & Development (100)
                'PHP Programming',
                'JavaScript Development',
                'Python Programming',
                'Java Development',
                'C++ Programming',
                'C# Development',
                'Ruby Programming',
                'Go Programming',
                'Swift Development',
                'Kotlin Programming',
                'TypeScript Development',
                'Rust Programming',
                'Scala Development',
                'Perl Scripting',
                'R Programming',
                'MATLAB Programming',
                'Objective-C Development',
                'Dart Programming',
                'Lua Scripting',
                'Shell Scripting',
                'PowerShell Scripting',
                'Bash Scripting',
                'HTML Development',
                'CSS Styling',
                'SASS Preprocessing',
                'LESS Preprocessing',
                'Bootstrap Framework',
                'Tailwind CSS',
                'React.js Development',
                'Vue.js Development',
                'Angular Development',
                'Node.js Development',
                'Express.js Framework',
                'Django Framework',
                'Flask Framework',
                'Laravel Framework',
                'Symfony Framework',
                'CodeIgniter Framework',
                'Ruby on Rails',
                'Spring Boot Development',
                'ASP.NET Development',
                'ASP.NET Core',
                'jQuery Library',
                'Next.js Framework',
                'Nuxt.js Framework',
                'Gatsby Framework',
                'GraphQL API',
                'REST API Development',
                'SOAP Web Services',
                'WebSocket Programming',
                'Microservices Architecture',
                'Serverless Computing',
                'API Design',
                'API Integration',
                'Software Architecture',
                'Object-Oriented Programming',
                'Functional Programming',
                'Test-Driven Development',
                'Behavior-Driven Development',
                'Code Review',
                'Code Refactoring',
                'Design Patterns',
                'SOLID Principles',
                'Clean Code',
                'Agile Development',
                'Scrum Methodology',
                'Version Control',
                'Git Version Control',
                'GitHub',
                'GitLab',
                'Bitbucket',
                'SVN',
                'Code Documentation',
                'Technical Documentation',
                'API Documentation',
                'Debugging',
                'Performance Optimization',
                'Memory Management',
                'Algorithm Design',
                'Data Structures',
                'Software Testing',
                'Unit Testing',
                'Integration Testing',
                'End-to-End Testing',
                'Automated Testing',
                'Manual Testing',
                'Regression Testing',
                'Load Testing',
                'Performance Testing',
                'Security Testing',
                'Penetration Testing',
                'Code Quality Assurance',
                'Continuous Integration',
                'Continuous Deployment',
                'DevOps Practices',
                'Infrastructure as Code',
                'Container Orchestration',
                'Cloud Computing',

                // Database & Data Management (50)
                'MySQL Database',
                'PostgreSQL Database',
                'MongoDB Database',
                'Microsoft SQL Server',
                'Oracle Database',
                'SQLite Database',
                'Redis Cache',
                'Elasticsearch',
                'Firebase Database',
                'Cassandra Database',
                'DynamoDB',
                'MariaDB Database',
                'Database Design',
                'Database Administration',
                'Database Optimization',
                'Query Optimization',
                'SQL Query Writing',
                'PL/SQL Programming',
                'T-SQL Programming',
                'NoSQL Databases',
                'Data Modeling',
                'ER Diagram Design',
                'Database Normalization',
                'Database Migration',
                'Data Warehousing',
                'ETL Processes',
                'Data Pipeline Development',
                'Big Data Processing',
                'Apache Hadoop',
                'Apache Spark',
                'Data Analytics',
                'Business Intelligence',
                'Data Visualization',
                'Tableau Software',
                'Power BI',
                'Google Analytics',
                'Data Mining',
                'Statistical Analysis',
                'Predictive Analytics',
                'Machine Learning',
                'Deep Learning',
                'Neural Networks',
                'TensorFlow',
                'PyTorch',
                'Scikit-learn',
                'Natural Language Processing',
                'Computer Vision',
                'Data Science',
                'Python for Data Science',
                'R for Statistics',

                // Cloud & DevOps (50)
                'Amazon Web Services',
                'Microsoft Azure',
                'Google Cloud Platform',
                'AWS EC2',
                'AWS S3',
                'AWS Lambda',
                'Azure Virtual Machines',
                'Azure DevOps',
                'Google Kubernetes Engine',
                'Docker Containerization',
                'Kubernetes Orchestration',
                'Jenkins Automation',
                'GitLab CI/CD',
                'GitHub Actions',
                'CircleCI',
                'Travis CI',
                'Terraform',
                'Ansible Automation',
                'Puppet Configuration',
                'Chef Configuration',
                'CloudFormation',
                'Linux System Administration',
                'Windows Server Administration',
                'Nginx Web Server',
                'Apache Web Server',
                'Load Balancing',
                'Server Monitoring',
                'Log Management',
                'Infrastructure Monitoring',
                'Application Performance Monitoring',
                'Cloud Security',
                'Network Security',
                'Firewall Configuration',
                'VPN Setup',
                'SSL/TLS Certificate Management',
                'Backup and Recovery',
                'Disaster Recovery Planning',
                'High Availability Design',
                'Scalability Planning',
                'Cloud Migration',
                'Hybrid Cloud Architecture',
                'Multi-Cloud Strategy',
                'Cost Optimization',
                'Resource Management',
                'Container Security',
                'Service Mesh',
                'Prometheus Monitoring',
                'Grafana Dashboards',
                'ELK Stack',
                'Splunk',

                // Mobile Development (30)
                'iOS App Development',
                'Android App Development',
                'React Native Development',
                'Flutter Development',
                'Swift Programming for iOS',
                'Kotlin for Android',
                'Xamarin Development',
                'Ionic Framework',
                'Mobile UI Design',
                'Mobile UX Design',
                'Responsive Mobile Design',
                'Mobile App Testing',
                'App Store Deployment',
                'Google Play Deployment',
                'Mobile Security',
                'Push Notification Implementation',
                'In-App Purchase Integration',
                'Mobile Analytics',
                'Firebase Integration',
                'Mobile API Integration',
                'Cross-Platform Development',
                'Progressive Web Apps',
                'Mobile Performance Optimization',
                'Offline Mobile Apps',
                'Location-Based Services',
                'Camera Integration',
                'Bluetooth Integration',
                'Mobile Payment Integration',
                'Mobile Game Development',
                'Augmented Reality Development',

                // Web Design & UI/UX (40)
                'User Interface Design',
                'User Experience Design',
                'Wireframing',
                'Prototyping',
                'User Research',
                'Usability Testing',
                'Information Architecture',
                'Interaction Design',
                'Visual Design',
                'Adobe Photoshop',
                'Adobe Illustrator',
                'Adobe XD',
                'Figma Design',
                'Sketch Design',
                'InVision Prototyping',
                'Responsive Web Design',
                'Mobile-First Design',
                'Typography',
                'Color Theory',
                'Layout Design',
                'Design Systems',
                'Component Libraries',
                'Accessibility Design',
                'WCAG Compliance',
                'Brand Identity Design',
                'Logo Design',
                'Icon Design',
                'Illustration',
                'Vector Graphics',
                'Motion Graphics',
                'Animation Design',
                'Adobe After Effects',
                'Adobe Premiere Pro',
                '3D Modeling',
                'Blender 3D',
                'Product Photography',
                'Photo Retouching',
                'Content Creation',

                // Business & Management (60)
                'Project Management',
                'Agile Project Management',
                'Scrum Master',
                'Kanban Management',
                'Waterfall Methodology',
                'Risk Management',
                'Stakeholder Management',
                'Resource Planning',
                'Budget Management',
                'Financial Planning',
                'Strategic Planning',
                'Business Analysis',
                'Requirements Gathering',
                'Process Improvement',
                'Change Management',
                'Team Leadership',
                'People Management',
                'Performance Management',
                'Conflict Resolution',
                'Negotiation Skills',
                'Decision Making',
                'Strategic Thinking',
                'Business Development',
                'Sales Management',
                'Account Management',
                'Customer Relationship Management',
                'Client Relations',
                'Business Strategy',
                'Market Analysis',
                'Competitive Analysis',
                'SWOT Analysis',
                'Product Management',
                'Product Strategy',
                'Roadmap Planning',
                'Feature Prioritization',
                'User Story Writing',
                'Backlog Management',
                'Sprint Planning',
                'Vendor Management',
                'Contract Negotiation',
                'Procurement',
                'Supply Chain Management',
                'Operations Management',
                'Quality Management',
                'Lean Management',
                'Six Sigma',
                'Business Process Modeling',
                'Workflow Optimization',
                'KPI Development',
                'Performance Metrics',
                'Reporting and Analytics',
                'Executive Presentations',
                'Board Presentations',
                'Investor Relations',
                'Fundraising',
                'Mergers and Acquisitions',
                'Due Diligence',
                'Corporate Governance',
                'Compliance Management',
                'Policy Development',

                // Marketing & Sales (40)
                'Digital Marketing',
                'Content Marketing',
                'Email Marketing',
                'Social Media Marketing',
                'Search Engine Optimization',
                'Search Engine Marketing',
                'Pay-Per-Click Advertising',
                'Google Ads Management',
                'Facebook Advertising',
                'Instagram Marketing',
                'LinkedIn Marketing',
                'Twitter Marketing',
                'TikTok Marketing',
                'YouTube Marketing',
                'Influencer Marketing',
                'Affiliate Marketing',
                'Marketing Automation',
                'HubSpot',
                'Salesforce CRM',
                'Marketing Analytics',
                'Conversion Rate Optimization',
                'A/B Testing',
                'Landing Page Optimization',
                'Copywriting',
                'Content Writing',
                'Blog Writing',
                'Technical Writing',
                'Brand Management',
                'Brand Strategy',
                'Public Relations',
                'Media Relations',
                'Event Marketing',
                'Trade Show Marketing',
                'Partnership Development',
                'Channel Marketing',
                'B2B Marketing',
                'B2C Marketing',
                'Customer Acquisition',
                'Lead Generation',
                'Sales Funnel Optimization',

                // Finance & Accounting (40)
                'Financial Accounting',
                'Management Accounting',
                'Cost Accounting',
                'Tax Accounting',
                'Bookkeeping',
                'Accounts Payable',
                'Accounts Receivable',
                'General Ledger',
                'Financial Reporting',
                'Financial Analysis',
                'Financial Modeling',
                'Budget Planning',
                'Forecasting',
                'Cash Flow Management',
                'Payroll Processing',
                'Tax Preparation',
                'Audit Support',
                'Internal Controls',
                'Reconciliation',
                'QuickBooks',
                'Xero Accounting',
                'SAP Finance',
                'Oracle Financials',
                'Excel Financial Analysis',
                'Investment Analysis',
                'Portfolio Management',
                'Risk Assessment',
                'Credit Analysis',
                'Treasury Management',
                'GAAP Standards',
                'IFRS Standards',
                'Financial Compliance',
                'Regulatory Reporting',
                'Variance Analysis',
                'Cost-Benefit Analysis',
                'Break-Even Analysis',
                'Wealth Management',
                'Asset Management',
                'Collections Management',

                // Healthcare (30)
                'Patient Care',
                'Clinical Assessment',
                'Medical Terminology',
                'Electronic Health Records',
                'Medical Coding',
                'Medical Billing',
                'HIPAA Compliance',
                'Nursing Care',
                'Medication Administration',
                'Vital Signs Monitoring',
                'Wound Care Management',
                'IV Therapy',
                'First Aid',
                'CPR Certified',
                'BLS Certified',
                'ACLS Certified',
                'Patient Education',
                'Care Coordination',
                'Case Management',
                'Healthcare Administration',
                'Medical Records Management',
                'Insurance Verification',
                'Prior Authorization',
                'Laboratory Procedures',
                'Phlebotomy',
                'Diagnostic Imaging',
                'Physical Therapy',
                'Occupational Therapy',
                'Mental Health Counseling',
                'Pharmacy Operations',

                // Hospitality & Customer Service (30)
                'Customer Service Excellence',
                'Guest Relations',
                'Complaint Resolution',
                'Active Listening',
                'Empathy',
                'Professional Communication',
                'Telephone Etiquette',
                'Email Etiquette',
                'Front Desk Operations',
                'Reception Management',
                'Concierge Services',
                'Hotel Operations',
                'Restaurant Service',
                'Food Service',
                'Bartending',
                'Culinary Arts',
                'Food Safety Certification',
                'Menu Planning',
                'Kitchen Management',
                'Event Planning',
                'Catering Management',
                'Banquet Coordination',
                'Reservation Systems',
                'POS System Operation',
                'Housekeeping Management',
                'Property Maintenance',
                'Inventory Management',
                'Vendor Coordination',
                'Quality Assurance',
                'Service Recovery',

                // Education & Training (20)
                'Classroom Teaching',
                'Online Teaching',
                'Curriculum Development',
                'Lesson Planning',
                'Student Assessment',
                'Educational Technology',
                'Learning Management Systems',
                'Instructional Design',
                'Training Delivery',
                'Workshop Facilitation',
                'Coaching and Mentoring',
                'Tutoring',
                'Special Education',
                'ESL Teaching',
                'Corporate Training',
                'Professional Development',
                'E-Learning Development',
                'Educational Research',
                'Classroom Management',
                'Student Engagement',

                // Administrative & Office (20)
                'Microsoft Office Suite',
                'Microsoft Word',
                'Microsoft Excel Advanced',
                'Microsoft PowerPoint',
                'Microsoft Outlook',
                'Google Workspace',
                'Data Entry',
                'Document Management',
                'Calendar Management',
                'Meeting Coordination',
                'Travel Arrangements',
                'Expense Reporting',
                'Filing Systems',
                'Office Management',
                'Executive Support',
                'Virtual Assistance',
                'Transcription',
                'Proofreading',
                'Professional Writing',
                'Organizational Skills',
            ];

            foreach ($skills as $index => $skill) {
                Skill::create([
                    'name' => $skill,
                ]);

                // Output progress every 50 skills
                if (($index + 1) % 50 == 0) {
                    echo "Created " . ($index + 1) . " skills...\n";
                }
            }

            DB::commit();

            echo "Successfully created " . count($skills) . " skills!\n";
        } catch (\Exception $e) {
            DB::rollBack();
            echo "Error: " . $e->getMessage() . "\n";
        }
    }
}
